import { normalizeBiomarkerName, type VitalityCategoryKey } from "@/lib/vitality/biomarker-metadata";
import type { Biomarker } from "@/lib/types/blood-report";

export type TestPriority = "essential" | "recommended" | "optional";

export interface RecommendedTest {
  id: string;
  name: string;
  category: VitalityCategoryKey;
  priority: TestPriority;
  /** Used to detect whether the user's own extracted biomarkers already
   *  cover this test — a separate, self-contained list from
   *  biomarker-metadata.ts, since several of these tests (HOMA-IR, Lp(a),
   *  Free Testosterone, DHEA-S, AM Cortisol, Zinc) aren't in that list at
   *  all. */
  aliases: string[];
  whyItMatters: string;
  labs: string[];
  medicareRebate: string;
  privateCost: string;
  fastingRequired: boolean;
  idealFrequency: string;
}

const COMMON_LABS = ["Healthscope", "Sullivan Nicolaides", "Melbourne Pathology", "ACL", "QML"];

// Draft copy — placeholder content per the build spec, to be refined
// later. "At minimum" per the brief runs to 37 entries once every listed
// category is covered; UI copy reads this array's length dynamically
// rather than hardcoding a count.
export const RECOMMENDED_TESTS: RecommendedTest[] = [
  // Metabolic
  {
    id: "hba1c",
    name: "HbA1c",
    category: "metabolic",
    priority: "essential",
    aliases: ["hba1c", "hemoglobin a1c", "haemoglobin a1c", "a1c", "glycated hemoglobin"],
    whyItMatters: "The single best marker of average blood sugar control over the past 2-3 months.",
    labs: COMMON_LABS,
    medicareRebate: "Usually rebatable with a GP referral.",
    privateCost: "$20-35",
    fastingRequired: false,
    idealFrequency: "Every 6-12 months.",
  },
  {
    id: "fasting_glucose",
    name: "Fasting Glucose",
    category: "metabolic",
    priority: "essential",
    aliases: ["glucose", "fasting glucose", "blood glucose", "fasting blood glucose"],
    whyItMatters: "A same-day snapshot of blood sugar, complementary to HbA1c's longer-term view.",
    labs: COMMON_LABS,
    medicareRebate: "Usually rebatable with a GP referral.",
    privateCost: "$15-25",
    fastingRequired: true,
    idealFrequency: "Every 6-12 months.",
  },
  {
    id: "fasting_insulin",
    name: "Fasting Insulin",
    category: "metabolic",
    priority: "recommended",
    aliases: ["insulin", "fasting insulin"],
    whyItMatters: "Rises years before glucose does — an early window into insulin resistance.",
    labs: COMMON_LABS,
    medicareRebate: "Rebate depends on symptoms or a metabolic risk referral.",
    privateCost: "$30-50",
    fastingRequired: true,
    idealFrequency: "Annually.",
  },
  {
    id: "triglycerides",
    name: "Triglycerides",
    category: "metabolic",
    priority: "essential",
    aliases: ["triglycerides", "trig"],
    whyItMatters: "A fat in the blood strongly tied to diet, alcohol, and metabolic health.",
    labs: COMMON_LABS,
    medicareRebate: "Usually rebatable as part of a standard lipid panel.",
    privateCost: "Included in most lipid panels",
    fastingRequired: true,
    idealFrequency: "Every 6-12 months.",
  },
  {
    id: "homa_ir",
    name: "HOMA-IR",
    category: "metabolic",
    priority: "optional",
    aliases: ["homa-ir", "homa ir", "homair"],
    whyItMatters: "A calculated insulin resistance score derived from fasting glucose and insulin.",
    labs: COMMON_LABS,
    medicareRebate: "Private pay only — it's a calculation, not a standalone test.",
    privateCost: "$0 if you already have glucose + insulin",
    fastingRequired: true,
    idealFrequency: "Annually, alongside fasting insulin.",
  },

  // Cardiovascular
  {
    id: "total_cholesterol",
    name: "Total Cholesterol",
    category: "cardiovascular",
    priority: "essential",
    aliases: ["cholesterol total", "total cholesterol", "cholesterol"],
    whyItMatters: "The headline cardiovascular risk number most GPs start with.",
    labs: COMMON_LABS,
    medicareRebate: "Usually rebatable with a GP referral.",
    privateCost: "Included in most lipid panels",
    fastingRequired: true,
    idealFrequency: "Every 12 months.",
  },
  {
    id: "hdl",
    name: "HDL Cholesterol",
    category: "cardiovascular",
    priority: "essential",
    aliases: ["hdl", "hdl cholesterol", "hdl-c"],
    whyItMatters: "\"Good\" cholesterol — higher levels are protective for the heart.",
    labs: COMMON_LABS,
    medicareRebate: "Usually rebatable as part of a standard lipid panel.",
    privateCost: "Included in most lipid panels",
    fastingRequired: true,
    idealFrequency: "Every 12 months.",
  },
  {
    id: "ldl",
    name: "LDL Cholesterol",
    category: "cardiovascular",
    priority: "essential",
    aliases: ["ldl", "ldl cholesterol", "ldl-c"],
    whyItMatters: "\"Bad\" cholesterol — the primary target for cardiovascular risk reduction.",
    labs: COMMON_LABS,
    medicareRebate: "Usually rebatable as part of a standard lipid panel.",
    privateCost: "Included in most lipid panels",
    fastingRequired: true,
    idealFrequency: "Every 12 months.",
  },
  {
    id: "vldl",
    name: "VLDL Cholesterol",
    category: "cardiovascular",
    priority: "optional",
    aliases: ["vldl", "vldl cholesterol"],
    whyItMatters: "A triglyceride-rich particle that also contributes to arterial plaque.",
    labs: COMMON_LABS,
    medicareRebate: "Usually included free in a standard lipid panel calculation.",
    privateCost: "Included in most lipid panels",
    fastingRequired: true,
    idealFrequency: "Every 12 months.",
  },
  {
    id: "non_hdl",
    name: "Non-HDL Cholesterol",
    category: "cardiovascular",
    priority: "recommended",
    aliases: ["non-hdl cholesterol", "non hdl cholesterol", "non-hdl-c"],
    whyItMatters: "All the artery-clogging cholesterol that isn't HDL — a strong single risk predictor.",
    labs: COMMON_LABS,
    medicareRebate: "Usually included free — it's calculated from the standard lipid panel.",
    privateCost: "Included in most lipid panels",
    fastingRequired: true,
    idealFrequency: "Every 12 months.",
  },
  {
    id: "apob",
    name: "ApoB",
    category: "cardiovascular",
    priority: "recommended",
    aliases: ["apob", "apolipoprotein b"],
    whyItMatters: "Counts the actual number of artery-clogging particles — many experts consider it more predictive than LDL alone.",
    labs: COMMON_LABS,
    medicareRebate: "Rebate depends on symptoms or a cardiovascular risk referral.",
    privateCost: "$40-60",
    fastingRequired: false,
    idealFrequency: "Annually, or once to establish a baseline.",
  },
  {
    id: "lpa",
    name: "Lp(a)",
    category: "cardiovascular",
    priority: "optional",
    aliases: ["lp(a)", "lpa", "lipoprotein a", "lipoprotein(a)"],
    whyItMatters: "A largely genetic cardiovascular risk factor — usually only needs testing once in a lifetime.",
    labs: COMMON_LABS,
    medicareRebate: "Rebate depends on family history of early heart disease.",
    privateCost: "$40-70",
    fastingRequired: false,
    idealFrequency: "Once, unless results are borderline.",
  },

  // Hormonal
  {
    id: "testosterone_total",
    name: "Testosterone (Total)",
    category: "hormonal",
    priority: "recommended",
    aliases: ["testosterone", "total testosterone"],
    whyItMatters: "A key driver of energy, muscle mass, mood, and libido in both men and women.",
    labs: COMMON_LABS,
    medicareRebate: "Usually rebatable if symptoms are present.",
    privateCost: "$30-50",
    fastingRequired: false,
    idealFrequency: "Annually, ideally an AM sample.",
  },
  {
    id: "shbg",
    name: "SHBG",
    category: "hormonal",
    priority: "optional",
    aliases: ["shbg", "sex hormone binding globulin"],
    whyItMatters: "Determines how much of your total testosterone is actually available to tissues.",
    labs: COMMON_LABS,
    medicareRebate: "Usually bundled with a testosterone request.",
    privateCost: "$20-35",
    fastingRequired: false,
    idealFrequency: "Alongside total testosterone.",
  },
  {
    id: "free_testosterone",
    name: "Free Testosterone",
    category: "hormonal",
    priority: "optional",
    aliases: ["free testosterone", "free t"],
    whyItMatters: "The biologically active fraction of testosterone — often more informative than the total.",
    labs: COMMON_LABS,
    medicareRebate: "Rebate depends on symptoms; often calculated from total testosterone + SHBG.",
    privateCost: "$0-40",
    fastingRequired: false,
    idealFrequency: "Alongside total testosterone.",
  },
  {
    id: "tsh",
    name: "TSH",
    category: "hormonal",
    priority: "essential",
    aliases: ["tsh", "thyroid stimulating hormone"],
    whyItMatters: "The primary screening test for an underactive or overactive thyroid.",
    labs: COMMON_LABS,
    medicareRebate: "Usually rebatable with a GP referral.",
    privateCost: "$20-35",
    fastingRequired: false,
    idealFrequency: "Every 12 months.",
  },
  {
    id: "free_t3",
    name: "Free T3",
    category: "hormonal",
    priority: "optional",
    aliases: ["free t3", "ft3", "triiodothyronine"],
    whyItMatters: "The active thyroid hormone that drives metabolism at the cellular level.",
    labs: COMMON_LABS,
    medicareRebate: "Rebate typically requires an abnormal TSH first.",
    privateCost: "$25-40",
    fastingRequired: false,
    idealFrequency: "Only if TSH is abnormal.",
  },
  {
    id: "free_t4",
    name: "Free T4",
    category: "hormonal",
    priority: "recommended",
    aliases: ["free t4", "ft4", "thyroxine"],
    whyItMatters: "The main thyroid hormone, converted to active T3 in tissues.",
    labs: COMMON_LABS,
    medicareRebate: "Rebate typically requires an abnormal TSH first.",
    privateCost: "$25-40",
    fastingRequired: false,
    idealFrequency: "Only if TSH is abnormal.",
  },
  {
    id: "dhea_s",
    name: "DHEA-S",
    category: "hormonal",
    priority: "optional",
    aliases: ["dhea-s", "dhea s", "dheas", "dehydroepiandrosterone sulfate"],
    whyItMatters: "An adrenal hormone and precursor to testosterone and estrogen — a useful marker of adrenal reserve.",
    labs: COMMON_LABS,
    medicareRebate: "Private pay only in most routine screening contexts.",
    privateCost: "$35-55",
    fastingRequired: false,
    idealFrequency: "Annually, or once to establish a baseline.",
  },
  {
    id: "cortisol_am",
    name: "Cortisol (AM)",
    category: "hormonal",
    priority: "optional",
    aliases: ["cortisol", "cortisol am", "morning cortisol", "am cortisol"],
    whyItMatters: "Your primary stress hormone — best measured first thing in the morning, when it should peak.",
    labs: COMMON_LABS,
    medicareRebate: "Rebate depends on symptoms suggesting an adrenal issue.",
    privateCost: "$25-40",
    fastingRequired: false,
    idealFrequency: "Annually, drawn before 9am.",
  },

  // Nutritional
  {
    id: "vitamin_d",
    name: "Vitamin D (25-hydroxyvitamin D)",
    category: "nutritional",
    priority: "essential",
    aliases: ["vitamin d", "25-hydroxyvitamin d", "vitamin d3", "25-oh vitamin d"],
    whyItMatters: "Critical for bone, immune, and hormonal health. Deficiency is common in Australia despite the sunlight.",
    labs: COMMON_LABS,
    medicareRebate: "Usually rebatable if symptoms suggest deficiency (fatigue, bone pain, hair loss).",
    privateCost: "$25-45",
    fastingRequired: false,
    idealFrequency: "Every 6 months, especially in winter.",
  },
  {
    id: "b12",
    name: "Vitamin B12",
    category: "nutritional",
    priority: "recommended",
    aliases: ["vitamin b12", "b12", "cobalamin"],
    whyItMatters: "Essential for nerve function and red blood cell production; deficiency can be subtle.",
    labs: COMMON_LABS,
    medicareRebate: "Usually rebatable with a GP referral.",
    privateCost: "$20-35",
    fastingRequired: false,
    idealFrequency: "Every 12 months.",
  },
  {
    id: "folate",
    name: "Folate",
    category: "nutritional",
    priority: "optional",
    aliases: ["folate", "folic acid", "vitamin b9"],
    whyItMatters: "Works alongside B12 for cell division and DNA synthesis — usually tested together.",
    labs: COMMON_LABS,
    medicareRebate: "Usually bundled with a B12 request.",
    privateCost: "$15-25",
    fastingRequired: false,
    idealFrequency: "Alongside B12.",
  },
  {
    id: "ferritin",
    name: "Ferritin",
    category: "nutritional",
    priority: "recommended",
    aliases: ["ferritin"],
    whyItMatters: "Reflects stored iron levels — low levels are a common, often-missed cause of fatigue.",
    labs: COMMON_LABS,
    medicareRebate: "Usually rebatable with a GP referral.",
    privateCost: "$20-35",
    fastingRequired: false,
    idealFrequency: "Every 12 months.",
  },
  {
    id: "iron_studies",
    name: "Iron Studies",
    category: "nutritional",
    priority: "optional",
    aliases: ["iron studies", "iron", "serum iron", "transferrin saturation"],
    whyItMatters: "A fuller picture of iron status than ferritin alone — useful for distinguishing deficiency from inflammation.",
    labs: COMMON_LABS,
    medicareRebate: "Usually rebatable with a GP referral.",
    privateCost: "$25-40",
    fastingRequired: false,
    idealFrequency: "Annually, or if ferritin is abnormal.",
  },
  {
    id: "magnesium",
    name: "Magnesium",
    category: "nutritional",
    priority: "optional",
    aliases: ["magnesium"],
    whyItMatters: "Involved in hundreds of enzymatic reactions, including energy production and muscle function.",
    labs: COMMON_LABS,
    medicareRebate: "Private pay only in most routine screening contexts.",
    privateCost: "$20-35",
    fastingRequired: false,
    idealFrequency: "Annually.",
  },
  {
    id: "zinc",
    name: "Zinc",
    category: "nutritional",
    priority: "optional",
    aliases: ["zinc"],
    whyItMatters: "Supports immune function, wound healing, and hormone production.",
    labs: COMMON_LABS,
    medicareRebate: "Private pay only in most routine screening contexts.",
    privateCost: "$25-40",
    fastingRequired: false,
    idealFrequency: "Annually.",
  },

  // Inflammation
  {
    id: "crp",
    name: "CRP (hs-CRP ideally)",
    category: "inflammation",
    priority: "essential",
    aliases: ["crp", "c-reactive protein", "hs-crp", "high sensitivity crp", "hscrp"],
    whyItMatters: "A general marker of inflammation, and the high-sensitivity version is a useful cardiovascular risk signal.",
    labs: COMMON_LABS,
    medicareRebate: "Usually rebatable with a GP referral.",
    privateCost: "$20-35",
    fastingRequired: false,
    idealFrequency: "Every 12 months.",
  },
  {
    id: "homocysteine",
    name: "Homocysteine",
    category: "inflammation",
    priority: "optional",
    aliases: ["homocysteine"],
    whyItMatters: "An amino acid linked to cardiovascular and cognitive risk when chronically elevated.",
    labs: COMMON_LABS,
    medicareRebate: "Rebate depends on cardiovascular risk factors.",
    privateCost: "$35-50",
    fastingRequired: true,
    idealFrequency: "Annually, or once to establish a baseline.",
  },
  {
    id: "esr",
    name: "ESR",
    category: "inflammation",
    priority: "optional",
    aliases: ["esr", "erythrocyte sedimentation rate", "sed rate"],
    whyItMatters: "An older, less specific inflammation marker, often used alongside CRP.",
    labs: COMMON_LABS,
    medicareRebate: "Usually rebatable with a GP referral.",
    privateCost: "$15-25",
    fastingRequired: false,
    idealFrequency: "Alongside CRP.",
  },

  // Liver & Kidney
  {
    id: "alt",
    name: "ALT",
    category: "liverKidney",
    priority: "essential",
    aliases: ["alt", "alanine aminotransferase", "sgpt"],
    whyItMatters: "A liver enzyme that rises when liver cells are stressed or damaged.",
    labs: COMMON_LABS,
    medicareRebate: "Usually rebatable as part of standard liver function tests.",
    privateCost: "Included in most LFT panels",
    fastingRequired: false,
    idealFrequency: "Every 12 months.",
  },
  {
    id: "ast",
    name: "AST",
    category: "liverKidney",
    priority: "recommended",
    aliases: ["ast", "aspartate aminotransferase", "sgot"],
    whyItMatters: "Another liver enzyme, also present in muscle and heart tissue — interpreted alongside ALT.",
    labs: COMMON_LABS,
    medicareRebate: "Usually rebatable as part of standard liver function tests.",
    privateCost: "Included in most LFT panels",
    fastingRequired: false,
    idealFrequency: "Every 12 months.",
  },
  {
    id: "ggt",
    name: "GGT",
    category: "liverKidney",
    priority: "optional",
    aliases: ["ggt", "gamma-glutamyl transferase", "gamma gt"],
    whyItMatters: "A liver enzyme sensitive to alcohol intake and bile duct issues.",
    labs: COMMON_LABS,
    medicareRebate: "Usually rebatable as part of standard liver function tests.",
    privateCost: "Included in most LFT panels",
    fastingRequired: false,
    idealFrequency: "Every 12 months.",
  },
  {
    id: "creatinine",
    name: "Creatinine",
    category: "liverKidney",
    priority: "essential",
    aliases: ["creatinine", "serum creatinine"],
    whyItMatters: "A muscle-derived waste product filtered by the kidneys — the core kidney function marker.",
    labs: COMMON_LABS,
    medicareRebate: "Usually rebatable as part of standard kidney function tests.",
    privateCost: "Included in most kidney function panels",
    fastingRequired: false,
    idealFrequency: "Every 12 months.",
  },
  {
    id: "egfr",
    name: "eGFR",
    category: "liverKidney",
    priority: "essential",
    aliases: ["egfr", "estimated gfr", "estimated glomerular filtration rate"],
    whyItMatters: "An estimate of how well your kidneys are filtering blood, calculated from creatinine.",
    labs: COMMON_LABS,
    medicareRebate: "Usually included free — it's calculated from creatinine.",
    privateCost: "Included with creatinine",
    fastingRequired: false,
    idealFrequency: "Every 12 months.",
  },
  {
    id: "urea",
    name: "Urea",
    category: "liverKidney",
    priority: "optional",
    aliases: ["urea", "blood urea nitrogen", "bun"],
    whyItMatters: "A waste product of protein metabolism, filtered by the kidneys — interpreted alongside creatinine.",
    labs: COMMON_LABS,
    medicareRebate: "Usually rebatable as part of standard kidney function tests.",
    privateCost: "Included in most kidney function panels",
    fastingRequired: false,
    idealFrequency: "Every 12 months.",
  },
  {
    id: "albumin",
    name: "Albumin",
    category: "liverKidney",
    priority: "recommended",
    aliases: ["albumin", "serum albumin"],
    whyItMatters: "A liver-made protein that reflects nutritional status and overall liver function.",
    labs: COMMON_LABS,
    medicareRebate: "Usually rebatable as part of standard liver function tests.",
    privateCost: "Included in most LFT panels",
    fastingRequired: false,
    idealFrequency: "Every 12 months.",
  },
];

export function getMissingTests(userBiomarkers: Biomarker[]): RecommendedTest[] {
  const covered = new Set(userBiomarkers.map((b) => normalizeBiomarkerName(b.name)));
  return RECOMMENDED_TESTS.filter(
    (test) => !test.aliases.some((alias) => covered.has(normalizeBiomarkerName(alias)))
  );
}
